# Commands to start on workspace startup
image:
  file: .gitpod.Dockerfile
tasks:
  - name: Terminal
    command: |
      bash
# Ports to expose on workspace startup
ports:
  - port: 3333
    onOpen: open-preview
vscode:
  extensions:
    - salesforce.salesforcedx-vscode
    - redhat.vscode-xml
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - 42crunch.vscode-openapi
    - yzane.markdown-pdf
    - tomoyukim.vscode-mermaid-editor
    - bierner.markdown-mermaid
    - jebbs.plantuml
    - myml.vscode-markdown-plantuml-preview
